language: ruby

sudo: false

cache:
  - apt
  - bundler
before_install:
  - gem install bundler

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x

addons:
  apt:
    packages:
      - graphviz

matrix:
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile-rails.4.1.x
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile-rails.4.2.x
    - rvm: 2.5.3
      gemfile: gemfiles/Gemfile-rails.4.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.4.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.4.2.x
  allow_failures:
    - rvm: ruby-head
